module.exports = [
  {
    name: "admin",
    fields: ["name,nick_name", "password", "status", "remarks"],
  },
  {
    name: "mail_log",
    fields: ["from", "to", "title", "content", "template", "send_time"],
  },
  {
    name: "permission",
    fields: ["permission_type", "permission_description"],
  },
  {
    name: "role_permission",
    fields: ["role_id", "permission_id"],
  },
  {
    name: "role",
    fields: ["role_name", "role_description"],
  },
  {
    name: "system_message",
    fields: ["user_id", "type", "content", "status"],
  },
  {
    name: "table_role_permission",
    fields: ["role_id", "permission_id", "table_name", "except_fields"],
  },
  {
    name: "task_log",
    fields: ["type", "content", "target", "status"],
  },
  {
    name: "currency",
    fields: ["coin", "dynamic_rate", "default_rate", "status"],
  },
  {
    name: "globalization",
    fields: [
      "user_agreement",
      "privacy_agreement",
      "trade",
      "about_us",
      "trading_rules",
      "locale",
    ],
  },
  {
    name: "site_article",
    fields: [
      "source_id",
      "type",
      "image_path",
      "author",
      "title",
      "summary",
      "content",
      "add_time",
      "views",
      "status",
    ],
  },
  {
    name: "site_info",
    fields: [
      "site_name",
      "site_logo",
      "site_host",
      "site_keywords",
      "site_description",
      "telegram",
      "whatsapp",
      "online_service",
      "service_mail",
      "official_mail",
      "system_maintenance",
    ],
  },
  {
    name: "site_notice",
    fields: ["title", "summary", "content"],
  },
  {
    name: "site_setting",
    fields: [
      "buy_fee",
      "buy_min_amount",
      "buy_min_nbr",
      "buy_max_nbr",
      "buy_max_amt_percent",
      "buy_same_times",
      "buy_same_nbr",
      "buy_nbr_times",
      "buy_nbr_lots",
      "sell_fee",
      "stay_fee",
      "duty_fee",
      "stay_max_days",
      "charge_min_amt",
      "force_stop_fee",
      "force_stop_percent",
      "hight_and_low",
      "with_min_amt",
      "crease_max_percent",
      "with_time_begin",
      "with_time_end",
      "trans_am_begin",
      "trans_am_end",
      "trans_pm_begin",
      "trans_pm_end",
      "trans_am_begin_us",
      "trans_am_end_us",
      "trans_pm_begin_us",
      "trans_pm_end_us",
      "with_fee_sigle",
      "with_fee_percent",
      "site_lever",
      "cant_sell_time",
      "kc_crease_max_percent",
      "stock_days",
      "stock_rate",
      "stock_chaa",
      "stock_chab",
      "stock_chac",
      "force_stop_remind_ration",
      "cy_crease_max_percent",
      "fall_buy_display",
      "trans_am_begin_hk",
      "trans_am_end_hk",
      "trans_pm_begin_hk",
      "trans_pm_end_hk",
      "vip_qc_max_amt",
    ],
  },
  {
    name: "site_wallet",
    fields: ["terminal", "address", "qr_code", "minimum", "remarks", "status"],
  },
  {
    name: "stock_subscribe",
    fields: [
      "name",
      "stock_type",
      "stock_description",
      "code",
      "gid",
      "price",
      "qty_issued",
      "price_earning_ratio",
      "is_show",
      "is_lock",
      "application_date",
      "acceptance_date",
      "issued_date",
    ],
  },
  {
    name: "user_deposit",
    fields: [
      "user_id",
      "from_account",
      "to_account",
      "amount",
      "trans_nbr",
      "paid_screenshot",
      "status",
    ],
  },
  {
    name: "user_withdrawal",
    fields: [
      "user_id",
      "amount",
      "withdrawal_fee",
      "withdrawal_addr",
      "status",
      "apply_time",
      "trans_time",
      "remark",
    ],
  },
  {
    name: "user",
    fields: [
      "nick_name",
      "phone",
      "mail",
      "password",
      "usdt_trc_addr",
      "usdt_erc_addr",
      "btc_erc_addr",
      "eth_erc_addr",
      "nrc_nbr",
      "nrc_name",
      "nrc_front",
      "nrc_back",
      "nrc_holding",
      "is_verified",
      "account_type",
      "usdt_amount",
      "enable_amount",
      "withdrawal_pass",
      "is_active",
      "is_locked",
      "registered_ip",
      "registered_addr",
      "registered_time",
    ],
  },
];
